# ===== Spring Boot Application =====
spring.application.name=quantity-measurement-app


spring.datasource.url=jdbc:mysql://localhost:3306/quantity_measurement_db
spring.datasource.username=root
spring.datasource.password=Dev#@20021

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=485783tyf83r38f78fedy8dfyy28fe8f7df8e7f8e7f8wvwv8vsf8v
jwt.expiration=86400000


# GitHub OAuth2
spring.security.oauth2.client.registration.github.client-id=Ov23liWSwkjj0RtZp3PD
spring.security.oauth2.client.registration.github.client-secret=a1c6d81b03c538321ba8e25f83fd8ef74efbe033

spring.security.oauth2.client.registration.github.scope=user:email


management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always