services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: security_db

    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - quantity-net

  eureka-server:
    image: httpsharsh/qma-eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - quantity-net
    restart: unless-stopped

  security-service:
    image: httpsharsh/qma-security-service:latest
    container_name: security-service
    ports:
      - "8081:8081"
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/security_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
      JWT_SECRET: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      GITHUB_CLIENT_ID: your_github_client_id
      GITHUB_CLIENT_SECRET: your_github_client_secret
    depends_on:
      - mysql
      - eureka-server
    networks:
      - quantity-net
    restart: unless-stopped

  quantity-measurement-app:
    image: httpsharsh/qma-quantity-measurement-app:latest
    container_name: quantity-measurement-app
    ports:
      - "8082:8082"
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/quantity_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
      JWT_SECRET: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    depends_on:
      - mysql
      - eureka-server
    networks:
      - quantity-net
    restart: unless-stopped

  api-gateway:
    image: httpsharsh/qma-api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka/
      JWT_SECRET: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    depends_on:
      - eureka-server
      - security-service
      - quantity-measurement-app
    networks:
      - quantity-net
    restart: unless-stopped

  caddy:
     image: caddy:2
     container_name: caddy
     ports:
       - "80:80"
       - "443:443"
     volumes:
       - ./Caddyfile:/etc/caddy/Caddyfile
       - caddy_data:/data
       - caddy_config:/config
     depends_on:
       - api-gateway
     networks:
       - quantity-net
     restart: unless-stopped

volumes:
  mysql_data:
  caddy_data:
  caddy_config:

networks:
  quantity-net:
    driver: bridge